[features]
seeds = false
skip-lint = false
[programs.devnet]
sapphire_auctions = "AUC3jnJ8x9U3GQjohgmd7r4ktVskfUt2Ef2CdFc4raHR"
[programs.mainnet]
sapphire_auctions = "SAPPozsZ9dApKRx4n4aMipFZ4pvH2QY9JmfLbks1UXo"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "https://devnet.helius-rpc.com/?api-key=66dcad9d-d5b4-4f99-b35a-93550c20c25a"
cluster = "https://mainnet.helius-rpc.com/?api-key=66dcad9d-d5b4-4f99-b35a-93550c20c25a"
wallet = "./program_auth.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
